In [10]:
import torch
import numpy as np
print('torch.version:',torch.__version__)

torch.version: 1.1.0



# torch 包函数
### 提供了多为张亮的数据结构以及其上的多种数学操作
### 这里只列举一些搭建网络时常用的张量操作

In [9]:
# torch.numel(input)
# 返回张量中的元素个数
a = torch.randn(1,2,3,4,5)
num = torch.numel(a)
print(num)
a = torch.zeros(4,4)
num = torch.numel(a)
print(num)

120
16


# 创建张量操作 

In [15]:
# torch.for_numpy(ndarray)
# 将numpy数组转换为张量，返回的张量与numpy数组共享内存空间，修改其中一个，另一个也会变化
a = np.array([1,2,3])
t = torch.from_numpy(a)
print(t)
t[0]=-1
print(a)

tensor([1, 2, 3])
[-1  2  3]


In [19]:
#torch.ones(*sizes, out=None)
#返回一个全为1的张量，形状为size
t = torch.ones(2, 3)
print(t)
t = torch.ones(5)
print(t)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([1., 1., 1., 1., 1.])


In [23]:
# torch.rand(*size, out=None)
# fanhui yige zhangliang ,baohan qujian [0,1)的均匀分布中抽取的一组随机数， 形状由size定义
t = torch.rand(4)
print(t)
t = torch.rand(2,3)
print(t)

tensor([0.2073, 0.2724, 0.6357, 0.8404])
tensor([[0.6538, 0.8037, 0.3969],
        [0.7419, 0.6290, 0.8508]])


In [27]:
# torch.randn(*sizes, out=None)
# 返回一个张量，包含了从标准正态分布中抽取一组随机数， 形状由size定义
t = torch.randn(4)
print(t)
t = torch.randn(2, 3)
print(t)

tensor([ 1.9027,  0.2626, -1.7842,  1.7237])
tensor([[-0.0926, -0.1079, -0.3787],
        [ 2.4367,  0.1863, -1.8357]])


In [29]:
# torch.randperm(n, out=None)
# 给定参数n， 返回一个从0到n-1的随机整数序列
t = torch.randperm(5)
print(t)

tensor([3, 0, 2, 4, 1])


In [31]:
# torch.zeros(*sizes, out=None)
#返回一个全为标量0的张量， 形状由size定义
t = torch.zeros(2,3)
print(t)
t = torch.zeros(5)
print(t)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0., 0., 0., 0.])


# 索引、切片、连接、换位

In [35]:
# torch.cat(inputs, dimension=0)
# 给定维度上对输入张量序列进行连接操作
# 可以看做是torch.split()和torch.chunk()的反操作
x = torch.randn(2, 3)
print(x)
y = torch.cat((x,x,x), dim=0)
print(y)
y = torch.cat((x,x,x), dim=1)
print(y)

tensor([[ 0.2658,  0.6475, -0.1520],
        [ 0.0197, -0.1919,  2.7836]])
tensor([[ 0.2658,  0.6475, -0.1520],
        [ 0.0197, -0.1919,  2.7836],
        [ 0.2658,  0.6475, -0.1520],
        [ 0.0197, -0.1919,  2.7836],
        [ 0.2658,  0.6475, -0.1520],
        [ 0.0197, -0.1919,  2.7836]])
tensor([[ 0.2658,  0.6475, -0.1520,  0.2658,  0.6475, -0.1520,  0.2658,  0.6475,
         -0.1520],
        [ 0.0197, -0.1919,  2.7836,  0.0197, -0.1919,  2.7836,  0.0197, -0.1919,
          2.7836]])


In [39]:
# torch.chunk(tensor, chunks, dim=0)
# 在给定维度上将输入张量进行分块
# chunks： 分块的个数
t = torch.randn(3, 3)
print(t)
a, b, c = torch.chunk(t, 3, dim=0)
print(a,b,c)
a, b, c = torch.chunk(t, 3, dim=1)
print(a,'\n',b,'\n',c)

tensor([[ 1.5200, -0.0619, -1.0714],
        [ 1.1593, -0.8721,  1.0234],
        [-0.4907,  0.8121, -0.1660]])
tensor([[ 1.5200, -0.0619, -1.0714]]) tensor([[ 1.1593, -0.8721,  1.0234]]) tensor([[-0.4907,  0.8121, -0.1660]])
tensor([[ 1.5200],
        [ 1.1593],
        [-0.4907]]) 
 tensor([[-0.0619],
        [-0.8721],
        [ 0.8121]]) 
 tensor([[-1.0714],
        [ 1.0234],
        [-0.1660]])


In [50]:
# torch.split(input, split_size, dim=0)
# 将输入张量分割相等形状的chunks， 如果沿指定dim的张量形状不能被整分，则最后一个小块会小于其他块
t = torch.randn(6,6)
print(t)
a, b = torch.split(t, 3, dim=0)
print(a, '\n',b)
a, b = torch.split(t, 3, dim=1)
print(a, '\n',b)

tensor([[ 1.4790, -0.9932, -0.3516,  0.1689,  0.2450,  0.1955],
        [ 0.3751, -1.7559, -0.2864, -0.9003, -0.0486,  1.5217],
        [-0.4601, -0.7660, -0.7716,  0.8151, -2.6800, -0.0153],
        [-0.5875, -0.1617,  0.3872,  0.4164,  0.1402, -1.4469],
        [ 0.3918,  1.8908, -0.2315, -0.9515,  0.4350,  1.8377],
        [-0.8952, -1.9530, -1.9013, -2.0954,  0.7590, -1.1621]])
tensor([[ 1.4790, -0.9932, -0.3516,  0.1689,  0.2450,  0.1955],
        [ 0.3751, -1.7559, -0.2864, -0.9003, -0.0486,  1.5217],
        [-0.4601, -0.7660, -0.7716,  0.8151, -2.6800, -0.0153]]) 
 tensor([[-0.5875, -0.1617,  0.3872,  0.4164,  0.1402, -1.4469],
        [ 0.3918,  1.8908, -0.2315, -0.9515,  0.4350,  1.8377],
        [-0.8952, -1.9530, -1.9013, -2.0954,  0.7590, -1.1621]])
tensor([[ 1.4790, -0.9932, -0.3516],
        [ 0.3751, -1.7559, -0.2864],
        [-0.4601, -0.7660, -0.7716],
        [-0.5875, -0.1617,  0.3872],
        [ 0.3918,  1.8908, -0.2315],
        [-0.8952, -1.9530, -1.9013]]) 
 te

In [42]:
# torch.index_select(input, dim, index, out=None)
# 沿着指定维度对输入进行切片
# 返回的张量不予原始张量共享内存
t = torch.randn(3, 4)
print(t)
indices = torch.LongTensor([0,2])
x = torch.index_select(t, 0, indices)
print(x)
x = torch.index_select(t, 1, indices)
print(x)

tensor([[-0.3616,  0.0512,  0.8111, -0.7402],
        [-1.0830, -1.5905, -0.0566,  1.4523],
        [-0.9813, -1.0178,  0.9778, -0.2004]])
tensor([[-0.3616,  0.0512,  0.8111, -0.7402],
        [-0.9813, -1.0178,  0.9778, -0.2004]])
tensor([[-0.3616,  0.8111],
        [-1.0830, -0.0566],
        [-0.9813,  0.9778]])


In [46]:
# torch.nonzero(input, out=None)
# 返回一个包含input中非零元素索引的张量
t = torch.eye(3,4)
print(t)
index = torch.nonzero(t)
print(index)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])
tensor([[0, 0],
        [1, 1],
        [2, 2]])


In [60]:
# torch.squeze(input , dim=None, out=None)
# 将输入张量形状中的1去除并返回，如输入形状是（aX1XbX1XcX1XdX1）输出为aXbXcXd
# 当指定dim时，那么挤压操作只在给定维度上作用
# 返回张量与输入张量共享内存

t = torch.zeros(2,1,2,1,2)
print(t.size())
y = torch.squeeze(t)
print(y.size())
y = torch.squeeze(t, dim=0)
print(y.size())
y = torch.squeeze(t, dim=1)
print(y.size())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 1, 2])


In [78]:
# torch.unsqueeze(input, dim, out=None)
# 返回一个新的张量，对输入的指定位置插入维度1
# 返回的张量与原始张量共享内存
t = torch.randn(2, 3)
print(t.size())
y = torch.unsqueeze(t, dim=0)
print(y.size())

torch.Size([2, 3])
torch.Size([1, 2, 3])


In [66]:
# torch.stack(seqyence, dim=0)
# sequence: 待连接的张量序列
# 与 torch.cat不同的是，stack会在指定dim创建新的维度
a = torch.randn(2,2)
b = torch.randn(2,2)
t = torch.stack((a, a, a), dim=0)
print(t)
print(t.size())

tensor([[[ 1.1541,  1.5992],
         [-0.0729, -0.2575]],

        [[ 1.1541,  1.5992],
         [-0.0729, -0.2575]],

        [[ 1.1541,  1.5992],
         [-0.0729, -0.2575]]])
torch.Size([3, 2, 2])


In [70]:
# torch.t(input, out=None)
# 输入一个2维矩阵，并转置，可视为torch.transpose(input,0,1)的简写函数
t =torch.randn(2, 3)
print(t)
y = torch.t(t)
print(y)

tensor([[-0.2412, -0.7360, -1.0196],
        [-2.2201,  0.1677,  1.4594]])
tensor([[-0.2412, -2.2201],
        [-0.7360,  0.1677],
        [-1.0196,  1.4594]])


In [74]:
# torch.transpose(input, dim0, dim1, out=None)
# 返回输入矩阵的转置，交换维度dim0与dim1，
# 输出张量与输出张量共享内存
t = torch.randn(2, 3, 4)
print(t)
y = torch.transpose(t, 0, 1)
print(y)

tensor([[[-0.3204,  1.1682, -0.0872, -1.9974],
         [-1.3310, -0.9180,  0.7218, -0.8850],
         [-0.0611, -1.2719,  0.7856, -0.5773]],

        [[-0.3415,  0.5506, -1.9949, -1.6552],
         [ 1.5703, -0.0792, -0.9050, -2.3225],
         [-0.1709,  0.8616,  1.6834,  0.1522]]])
tensor([[[-0.3204,  1.1682, -0.0872, -1.9974],
         [-0.3415,  0.5506, -1.9949, -1.6552]],

        [[-1.3310, -0.9180,  0.7218, -0.8850],
         [ 1.5703, -0.0792, -0.9050, -2.3225]],

        [[-0.0611, -1.2719,  0.7856, -0.5773],
         [-0.1709,  0.8616,  1.6834,  0.1522]]])
