In [10]:
import torch
import numpy as np
print('torch.version:',torch.__version__)

torch.version: 1.1.0



# torch 包函数
### 提供了多为张量的数据结构以及其上的多种数学操作
### 这里只列举一些搭建网络时常用的张量操作

In [9]:
# torch.numel(input)
# 返回张量中的元素个数
a = torch.randn(1,2,3,4,5)
num = torch.numel(a)
print(num)
a = torch.zeros(4,4)
num = torch.numel(a)
print(num)

120
16


# 创建张量操作

In [15]:
# torch.for_numpy(ndarray)
# 将numpy数组转换为张量，返回的张量与numpy数组共享内存空间，修改其中一个，另一个也会变化
a = np.array([1,2,3])
t = torch.from_numpy(a)
print(t)
t[0]=-1
print(a)

tensor([1, 2, 3])
[-1  2  3]


In [19]:
#torch.ones(*sizes, out=None)
#返回一个全为1的张量，形状为size
t = torch.ones(2, 3)
print(t)
t = torch.ones(5)
print(t)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([1., 1., 1., 1., 1.])


In [23]:
# torch.rand(*size, out=None)
# fanhui yige zhangliang ,baohan qujian [0,1)的均匀分布中抽取的一组随机数， 形状由size定义
t = torch.rand(4)
print(t)
t = torch.rand(2,3)
print(t)

tensor([0.2073, 0.2724, 0.6357, 0.8404])
tensor([[0.6538, 0.8037, 0.3969],
        [0.7419, 0.6290, 0.8508]])


In [27]:
# torch.randn(*sizes, out=None)
# 返回一个张量，包含了从标准正态分布中抽取一组随机数， 形状由size定义
t = torch.randn(4)
print(t)
t = torch.randn(2, 3)
print(t)

tensor([ 1.9027,  0.2626, -1.7842,  1.7237])
tensor([[-0.0926, -0.1079, -0.3787],
        [ 2.4367,  0.1863, -1.8357]])


In [29]:
# torch.randperm(n, out=None)
# 给定参数n， 返回一个从0到n-1的随机整数序列
t = torch.randperm(5)
print(t)

tensor([3, 0, 2, 4, 1])


In [31]:
# torch.zeros(*sizes, out=None)
#返回一个全为标量0的张量， 形状由size定义
t = torch.zeros(2,3)
print(t)
t = torch.zeros(5)
print(t)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0., 0., 0., 0.])


# 索引、切片、连接、换位

In [35]:
# torch.cat(inputs, dimension=0)
# 给定维度上对输入张量序列进行连接操作
# 可以看做是torch.split()和torch.chunk()的反操作
x = torch.randn(2, 3)
print(x)
y = torch.cat((x,x,x), dim=0)
print(y)
y = torch.cat((x,x,x), dim=1)
print(y)

tensor([[ 0.2658,  0.6475, -0.1520],
        [ 0.0197, -0.1919,  2.7836]])
tensor([[ 0.2658,  0.6475, -0.1520],
        [ 0.0197, -0.1919,  2.7836],
        [ 0.2658,  0.6475, -0.1520],
        [ 0.0197, -0.1919,  2.7836],
        [ 0.2658,  0.6475, -0.1520],
        [ 0.0197, -0.1919,  2.7836]])
tensor([[ 0.2658,  0.6475, -0.1520,  0.2658,  0.6475, -0.1520,  0.2658,  0.6475,
         -0.1520],
        [ 0.0197, -0.1919,  2.7836,  0.0197, -0.1919,  2.7836,  0.0197, -0.1919,
          2.7836]])


In [39]:
# torch.chunk(tensor, chunks, dim=0)
# 在给定维度上将输入张量进行分块
# chunks： 分块的个数
t = torch.randn(3, 3)
print(t)
a, b, c = torch.chunk(t, 3, dim=0)
print(a,b,c)
a, b, c = torch.chunk(t, 3, dim=1)
print(a,'\n',b,'\n',c)

tensor([[ 1.5200, -0.0619, -1.0714],
        [ 1.1593, -0.8721,  1.0234],
        [-0.4907,  0.8121, -0.1660]])
tensor([[ 1.5200, -0.0619, -1.0714]]) tensor([[ 1.1593, -0.8721,  1.0234]]) tensor([[-0.4907,  0.8121, -0.1660]])
tensor([[ 1.5200],
        [ 1.1593],
        [-0.4907]]) 
 tensor([[-0.0619],
        [-0.8721],
        [ 0.8121]]) 
 tensor([[-1.0714],
        [ 1.0234],
        [-0.1660]])


In [50]:
# torch.split(input, split_size, dim=0)
# 将输入张量分割相等形状的chunks， 如果沿指定dim的张量形状不能被整分，则最后一个小块会小于其他块
t = torch.randn(6,6)
print(t)
a, b = torch.split(t, 3, dim=0)
print(a, '\n',b)
a, b = torch.split(t, 3, dim=1)
print(a, '\n',b)

tensor([[ 1.4790, -0.9932, -0.3516,  0.1689,  0.2450,  0.1955],
        [ 0.3751, -1.7559, -0.2864, -0.9003, -0.0486,  1.5217],
        [-0.4601, -0.7660, -0.7716,  0.8151, -2.6800, -0.0153],
        [-0.5875, -0.1617,  0.3872,  0.4164,  0.1402, -1.4469],
        [ 0.3918,  1.8908, -0.2315, -0.9515,  0.4350,  1.8377],
        [-0.8952, -1.9530, -1.9013, -2.0954,  0.7590, -1.1621]])
tensor([[ 1.4790, -0.9932, -0.3516,  0.1689,  0.2450,  0.1955],
        [ 0.3751, -1.7559, -0.2864, -0.9003, -0.0486,  1.5217],
        [-0.4601, -0.7660, -0.7716,  0.8151, -2.6800, -0.0153]]) 
 tensor([[-0.5875, -0.1617,  0.3872,  0.4164,  0.1402, -1.4469],
        [ 0.3918,  1.8908, -0.2315, -0.9515,  0.4350,  1.8377],
        [-0.8952, -1.9530, -1.9013, -2.0954,  0.7590, -1.1621]])
tensor([[ 1.4790, -0.9932, -0.3516],
        [ 0.3751, -1.7559, -0.2864],
        [-0.4601, -0.7660, -0.7716],
        [-0.5875, -0.1617,  0.3872],
        [ 0.3918,  1.8908, -0.2315],
        [-0.8952, -1.9530, -1.9013]]) 
 te

In [42]:
# torch.index_select(input, dim, index, out=None)
# 沿着指定维度对输入进行切片
# 返回的张量不予原始张量共享内存
t = torch.randn(3, 4)
print(t)
indices = torch.LongTensor([0,2])
x = torch.index_select(t, 0, indices)
print(x)
x = torch.index_select(t, 1, indices)
print(x)

tensor([[-0.3616,  0.0512,  0.8111, -0.7402],
        [-1.0830, -1.5905, -0.0566,  1.4523],
        [-0.9813, -1.0178,  0.9778, -0.2004]])
tensor([[-0.3616,  0.0512,  0.8111, -0.7402],
        [-0.9813, -1.0178,  0.9778, -0.2004]])
tensor([[-0.3616,  0.8111],
        [-1.0830, -0.0566],
        [-0.9813,  0.9778]])


In [46]:
# torch.nonzero(input, out=None)
# 返回一个包含input中非零元素索引的张量
t = torch.eye(3,4)
print(t)
index = torch.nonzero(t)
print(index)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])
tensor([[0, 0],
        [1, 1],
        [2, 2]])


In [60]:
# torch.squeze(input , dim=None, out=None)
# 将输入张量形状中的1去除并返回，如输入形状是（aX1XbX1XcX1XdX1）输出为aXbXcXd
# 当指定dim时，那么挤压操作只在给定维度上作用
# 返回张量与输入张量共享内存

t = torch.zeros(2,1,2,1,2)
print(t.size())
y = torch.squeeze(t)
print(y.size())
y = torch.squeeze(t, dim=0)
print(y.size())
y = torch.squeeze(t, dim=1)
print(y.size())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 1, 2])


In [78]:
# torch.unsqueeze(input, dim, out=None)
# 返回一个新的张量，对输入的指定位置插入维度1
# 返回的张量与原始张量共享内存
t = torch.randn(2, 3)
print(t.size())
y = torch.unsqueeze(t, dim=0)
print(y.size())

torch.Size([2, 3])
torch.Size([1, 2, 3])


In [66]:
# torch.stack(seqyence, dim=0)
# sequence: 待连接的张量序列
# 与 torch.cat不同的是，stack会在指定dim创建新的维度
a = torch.randn(2,2)
b = torch.randn(2,2)
t = torch.stack((a, a, a), dim=0)
print(t)
print(t.size())

tensor([[[ 1.1541,  1.5992],
         [-0.0729, -0.2575]],

        [[ 1.1541,  1.5992],
         [-0.0729, -0.2575]],

        [[ 1.1541,  1.5992],
         [-0.0729, -0.2575]]])
torch.Size([3, 2, 2])


In [70]:
# torch.t(input, out=None)
# 输入一个2维矩阵，并转置，可视为torch.transpose(input,0,1)的简写函数
t =torch.randn(2, 3)
print(t)
y = torch.t(t)
print(y)

tensor([[-0.2412, -0.7360, -1.0196],
        [-2.2201,  0.1677,  1.4594]])
tensor([[-0.2412, -2.2201],
        [-0.7360,  0.1677],
        [-1.0196,  1.4594]])


In [74]:
# torch.transpose(input, dim0, dim1, out=None)
# 返回输入矩阵的转置，交换维度dim0与dim1，
# 输出张量与输出张量共享内存
t = torch.randn(2, 3, 4)
print(t)
y = torch.transpose(t, 0, 1)
print(y)

tensor([[[-0.3204,  1.1682, -0.0872, -1.9974],
         [-1.3310, -0.9180,  0.7218, -0.8850],
         [-0.0611, -1.2719,  0.7856, -0.5773]],

        [[-0.3415,  0.5506, -1.9949, -1.6552],
         [ 1.5703, -0.0792, -0.9050, -2.3225],
         [-0.1709,  0.8616,  1.6834,  0.1522]]])
tensor([[[-0.3204,  1.1682, -0.0872, -1.9974],
         [-0.3415,  0.5506, -1.9949, -1.6552]],

        [[-1.3310, -0.9180,  0.7218, -0.8850],
         [ 1.5703, -0.0792, -0.9050, -2.3225]],

        [[-0.0611, -1.2719,  0.7856, -0.5773],
         [-0.1709,  0.8616,  1.6834,  0.1522]]])


# Torch.nn包相关模块介绍

# class torch.nn.Module() 
# 所有网络的基类

In [2]:
# modules也可以抱哈其他Modules，允许使用树结构嵌入他们，也可以将子模块复制给模型属性
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F

class Model(nn.Module):
    def __init__(self):
        super(Model,self).__init__()
        self.conv1 = nn.Conv2d(1, 20, 3)
        self.conv2 = nn.Conv2d(20, 20, 3)
        
    def forward(self, x):
        x = F.relu(self.conv1(x))
        return F.relu(self.conv2(x))

In [4]:
# cpu(): 将所有模型参数和buffers复制到cpu
# gpu(): 将所有模型参数个buffers复制到gpu
# eval(): 将模型设置为evalution模式，仅仅当模型中有Droupout和BatchNorm时才会有影响
# train(): 将模型设置为train模式，仅仅当模型中有Droupout和BatchNorm时才会有影响
# parameters(): 返回一个包含模型所有参数的迭代
# 一般用来当做oprimizer的参数
# zero_grad()：将module中的所有模型参数的梯度设置为0

In [8]:
# class torch.nn.Seqiential()
# 一个时序容器，Modules会议他们传入的顺序被添加到容器中，
model = nn.Sequential(
                nn.Conv2d(1, 20, 5),
                nn.ReLU(),
                nn.Conv2d(20, 20, 5),
                nn.ReLU()
                )


In [15]:
# class torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride=1, 
#                                         padding=0, dilation=1, groups=1, bias=True)
# Parameters:
# diliation:卷积核元素之间的间距，当大于1时即形成空洞卷积
# groups: 控制输入和输出之间的连接： group=1，输出是所有的输入的卷积；
#              group=2，此时相当于有并排的两个卷积层，每个卷积层计算输入通道的一半，
#             并且产生的输出是输出通道的一半，随后将这两个输出连接起来。
m = nn.Conv2d(16, 33, (3, 5), stride=2, padding=(4, 2), dilation=(3, 1))
input = torch.autograd.Variable(torch.randn(20, 16, 50, 100))
output = m(input)
print(output.size())

torch.Size([20, 33, 26, 50])


In [18]:
# class torch.nn.ConvTranspose2d(input_channels, output_channels, kenel_size，
#                           stride=1, padding=0, output_padding=0, groups=1, bias=True)
# 二维的转置卷积操作，科士威解卷积操作，但不是真正的解卷积操作
input = torch.autograd.Variable(torch.randn(1, 16, 12, 12))
downsample = nn.Conv2d(16, 16, 3, stride=2, padding=1)
upsample = nn.ConvTranspose2d(16, 16, 3, stride=2, padding=1)
h = downsample(input)
print(h.size())
h1 = upsample(h, output_size=input.size())
h2= upsample(h)
print(h1.size())
print(h2.size())

torch.Size([1, 16, 6, 6])
torch.Size([1, 16, 12, 12])
torch.Size([1, 16, 11, 11])


In [22]:
# torch.nn.MaxPool2d(kenel_size, stride=None, padding=0,
#                    dilation=1, return_indices=False, ceil_mode=False)
# 最大二维池化操作，很好理解
# parameters：
# return_indices: 如果为True，会返回输出最大值的序号，对上采样有帮助
# ceil_mode: 如果为True，计算输出信号大小的时候，会向上取整，代替默认的向下取整
m = nn.MaxPool2d(2)
input = torch.autograd.Variable(torch.randn(20, 16, 50, 32))
output = m(input)
print(output.size())

torch.Size([20, 16, 25, 16])


In [30]:
# torch.nn.MaxUppool2d(kernel_size, stride=None. padding=0)
# MaxPool2d的逆过程， 并不是完整的逆过程，因为在maxpool2d的过程中，一些最大值已经丢失
# 注意：Maxpool2d可以将多个输入大小映射到相同的输出大小，因此反演过程可能会变得模棱两可，
#       为了适应这一点，可以在调用中将输出大小output_size作为额外的参数传入
# 输入：input：需要转换的tensor
#        indices：Maxpool2d的索引号
#        output_size:一个指定输出大小的torch.size
pool = nn.MaxPool2d(2, return_indices=True)
unpool = nn.MaxUnpool2d(2)
input = Variable(torch.Tensor([[[[1, 2, 3, 4],
                                 [5, 6, 7, 8],
                                [9, 10, 11, 12],
                                [13, 14, 15, 16]]]]))
print(input.size())
output, indices = pool(input)
output1 = unpool(output, indices)
print(output1)

output2 = unpool(output, indices, output_size=torch.Size([1, 1, 5, 5]))
print(output2)

torch.Size([1, 1, 4, 4])
tensor([[[[ 0.,  0.,  0.,  0.],
          [ 0.,  6.,  0.,  8.],
          [ 0.,  0.,  0.,  0.],
          [ 0., 14.,  0., 16.]]]])
tensor([[[[ 0.,  0.,  0.,  0.,  0.],
          [ 6.,  0.,  8.,  0.,  0.],
          [ 0.,  0.,  0., 14.,  0.],
          [16.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]]]])


# 非线性激活函数

In [32]:
# class torch.nn.Softmax()
# 对n维张量运用siftmax函数，将张量的每个元素缩放到0~1，且和为1
m = nn.Softmax(dim=1)
input = Variable(torch.randn(2, 3))
output = m(input)
print(input)
print(output)

tensor([[ 0.0375,  0.7673, -0.6387],
        [ 2.2014,  0.4968, -0.2370]])
tensor([[0.2791, 0.5790, 0.1419],
        [0.7879, 0.1433, 0.0688]])


In [243]:
# class torch.nn.ReLU(inplace=False)
# inplace:选择是否进行覆盖运算
m = nn.ReLU(inplace=True)
input = Variable(torch.randn(2))
print(input)
output = m(input)
print(output)
print(F.relu(input))

tensor([-1.5915,  1.2821])
tensor([0.0000, 1.2821])
tensor([0.0000, 1.2821])


In [58]:
# class torch.nn.ReLU6(implace=False)
# in_place:选择是否进行覆盖运算，若果覆盖，可以节省内存
# x = min(max(0, x), 6) 最大激活值为6
m = nn.ReLU6()
input = Variable(torch.randn(2))
print(input)
output = m(input)
print(output)
print(F.relu(input))

tensor([-0.0156,  0.6847])
tensor([0.0000, 0.6847])
tensor([0.0000, 0.6847])


In [67]:
# class torch.nn.Tanh
# 对每个输入元素， 计算f(x)=(e^x-e^-x)/(e^x+e^-x)
# 将输入限制在0~1
m = nn.Tanh()
input = Variable(torch.randn(2))
print(input)
print(m(input))

tensor([1.1633, 1.0373])
tensor([0.8221, 0.7768])


In [76]:

input = Variable(torch.randn(2,2))
print(input)
print(F.softmax(input, dim=0))

tensor([[-1.0698,  0.5344],
        [ 0.5783,  0.6368]])
tensor([[0.1614, 0.4744],
        [0.8386, 0.5256]])


In [82]:
# class torch.nn.BatchNorm2d(num_features,eps=1e-5,momentum=0.1,
#                           affine=True)
# 在每个batch数据中，计算输入各个维度的均值与标准差，
# num_features:来自期望输入的特征数
#  eps:为保证数据稳定性（坟墓不能趋近或取0）给分母加上一个值， 默认1e-5
# momentum:动态均值可动态方差所使用的栋梁，默认0.1
# affine:为True时，给改成添加可学习的仿射变换参数
m = nn.BatchNorm2d(2)
m1 = nn.BatchNorm2d(2, affine=True)
input = Variable(torch.randn(2, 2, 2, 3))
output1 = m(input)
output2 = m1(input)
print(input)
print(output1)

tensor([[[[ 0.6036, -0.1050, -0.5292],
          [ 0.3276,  0.9532, -0.8595]],

         [[-0.6410, -0.7502, -0.0283],
          [-1.2451, -0.2500, -0.4774]]],


        [[[-1.5284, -1.1040, -0.3194],
          [-1.1344, -1.2175,  1.3156]],

         [[-0.6666,  1.5257,  0.4784],
          [ 0.6649,  2.0937, -0.3757]]]])
tensor([[[[ 0.0720,  0.0155, -0.0183],
          [ 0.0500,  0.0998, -0.0446]],

         [[-0.2334, -0.2715, -0.0194],
          [-0.4444, -0.0968, -0.1763]]],


        [[[-0.0979, -0.0641, -0.0016],
          [-0.0665, -0.0731,  0.1287]],

         [[-0.2423,  0.5232,  0.1575],
          [ 0.2226,  0.7216, -0.1408]]]], grad_fn=<NativeBatchNormBackward>)


# Linner layers

In [84]:
# class torch.nn.Linear(in_features, out_features, bias=True)
# 对输入数据做线性变换y=Ax+b
m = nn.Linear(20, 30)
input = Variable(torch.randn(2, 20))
output = m(input)
print(input.size())
print(output.size())

torch.Size([2, 20])
torch.Size([2, 30])


# Dropout layers

In [214]:
# calss torch.nn.Dropout(p=0.2, inplace=False)
# 随机将输入张量中部分元素置为0，对于每次前向调用，置0的元素都是随机的
# p:将元素置0的概率
# inplace:若为True，会在原地执行操作
m = nn.Dropout(p=0.5)
input = Variable(torch.randn(2, 6, 3))
output = m(input)
# print(input)
print(output)

tensor([[[ 0.0000, -2.6564, -0.0000],
         [ 1.1167,  0.0000, -1.3734],
         [-0.0000, -0.8802,  0.0000],
         [-0.1679, -0.0000,  0.8384],
         [ 0.0000,  0.6846,  0.0000],
         [-2.1018, -0.0000, -2.1762]],

        [[-0.0000, -1.1254,  0.0000],
         [ 1.4707,  0.0000,  0.4841],
         [-0.0000,  3.8631,  0.0000],
         [-1.0782,  0.0000, -0.9463],
         [-0.0000, -3.2843,  0.0000],
         [-1.6249, -0.0000,  1.2248]]])


In [215]:
# class torch.nn.Dropout2d()
# 与Dropout不同的是，Droupout是对每个元素进行随机的置0，而Dropout2d是对dim=0的通道全部进行置0
# 像在论文Efficient Object Localization Using Convolutional Networks，
# 如果特征图中相邻像素是强相关的（在前几层卷积层很常见），那么iid dropout不会归一化激活，而只会降低学习率。
n = nn.Dropout2d(p=0.5)
input = Variable(torch.randn(2, 6, 3))
output = n(input)
print(output)

tensor([[[ 0.0000,  0.0000,  0.0000],
         [ 5.5649,  0.3528,  1.0334],
         [-0.0000,  0.0000,  0.0000],
         [ 2.1818, -0.4656, -0.2783],
         [-0.0000, -0.0000,  0.0000],
         [-2.2832,  2.4742, -1.3990]],

        [[-0.0000,  0.0000, -0.0000],
         [ 0.3037, -4.2412, -1.9647],
         [-0.0000, -0.0000,  0.0000],
         [ 0.0320, -4.7925, -1.3204],
         [-0.0000,  0.0000, -0.0000],
         [ 2.8148, -2.5035, -1.5152]]])


# Loss functions

In [1]:
# class torch.nn.L1Loss(size_average=True)
# 创建一个衡量输入与目标y之间的绝对值的平均值的标准差
# 如果size_average=False，那么求出来的绝对值的和不会除以n

# class torch.nn.MSELoss(size_average=True)
# 衡量预测与目标之间的均方误差

# class torch.nn.NLLLoss(weight=None, sizeO_average=True)
# 用于训练一个n类的分类器

# class torch.nn.CrossEntropyLoss(weight=None, size_average=True)
# 将LogSoftmax和NLLLoss集成到一个类中
# 通常用于训练一个多分类器

# class torch.nn.BCELoss(weight=None, size_average=True)
# 计算预测与目标的二进制交叉熵

# UPsampling Layers

In [11]:
# class torch.nn.UpsamplingNearest2d(size = None, scale_factor=None)
# 对于多通道输入进行最近邻上采样
# 可以通过size和scale_factor指定上采样后的大小
# 当给定size时，输出图想大小将是size
input = Variable(torch.Tensor([[[[1,2],[3,4]]]]))
print(input)
upsam = torch.nn.UpsamplingNearest2d(scale_factor=2)
output = upsam(input)
print(output)

tensor([[[[1., 2.],
          [3., 4.]]]])
tensor([[[[1., 1., 2., 2.],
          [1., 1., 2., 2.],
          [3., 3., 4., 4.],
          [3., 3., 4., 4.]]]])


In [13]:
# class torch.nn.UpsampingBilinear2d(size=None, scale_factor=None)
# 对多通道输入进行线性上采样
# 同样通过size或scale_factor来决定输出大小
input = Variable(torch.Tensor([[[[1,2],[3,4]]]]))
print(input)
upsam = torch.nn.UpsamplingBilinear2d(scale_factor=2)
output = upsam(input)
print(output)

tensor([[[[1., 2.],
          [3., 4.]]]])
tensor([[[[1.0000, 1.3333, 1.6667, 2.0000],
          [1.6667, 2.0000, 2.3333, 2.6667],
          [2.3333, 2.6667, 3.0000, 3.3333],
          [3.0000, 3.3333, 3.6667, 4.0000]]]])


In [ ]:
# Mutil-GPU layers
# class torch.nn.DataParallel(module, devices_ids=None, output_device=None, deim=0)
# 在模块级别上实现数据并行
# 此容器将mini-batch划分到不同的设备上来实现戈丁module的并行，在forwaed过程中，module会在每个设备上都复制一遍，每个副本都会处理部分输入，
# 在backward过程中，副本级的梯度会累加到原始的module上
# catch的大小应该大于所使用的GPU数量，还应该是GPU数量的整数倍
# 参数说明：
# module：要被并行执行的模型
# device_ids：CUDA设备，默认所有设备
# output_device:输出设备，默认为device_ids[0]

net = torch.nn.DataParallel(model, device_ids=[1,2,3])
output = net(input_var)

# 特别说明
## 关于torch.nn 和torch.nn.functional的区别与联系
### 在写 PyTorch 代码时，我们会发现在 torch.nn.xxx 和 torch.nn.functional.xxx 中有一些功能重复的操作，比如卷积、激活、池化。这些操作有什么不同？各有什么用处？

In [ ]:
# 首先我们来看一下torch.nn.Conv2d和torch.nn.functional.conv2d是如何定义的
# torch.nn.Conv2d
class torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=True, padding_mode='zeros')
# torch.nn.functional.conv2d
torch.nn.functional.conv2d(input, weight, bias=None, stride=1, padding=0, dilation=1, groups=1) → Tensor

# 我们可以发现，nn.Conv2d是一个类，而nn.functional.conv2d是一个函数
# 此外还有以下几点不同：
# 1.两者调用方式不同，调用nn.xxx时要先在里面传入超参数，然后在将数据以函数调用的方式传入nn.xxx，如
input = torch.randn(64, 3, 224, 224)
conv = nn.Conv2d(in_channel=3, out_chaneels=64, kernel_size=4, paddin=1)
out = conv(input)
# 而nn.functional.xxx则要同时输入数据和weight，bias等参数
weight = torch.randn(64, 3, 3, 3)
bias = torch.randn(64)
out = nn.functional.conv2d(inputs, weight, bias, padding=1)
# 2.nn.xxx能够放在nn.Sequential中，而nn.functional.xxx不行
# 3.nn.functional.xxx需要自己定义weight，每次调用时都要手动传入weight和bias，而nn.xxx则不用
class CNN(nn.Module):
    def __init__(self)：
        super(CNN, self).__init__()
        
        self.conv_1 = nn.Conv2d(1, 16, 5, padding=0)
        self.relu_1 = nn.ReLU(inplace=True)
        self.maxpool_1 = nn.MaxPool2d(kernel_size=2)
        
        self.conv_2 = nn.Conv2d(16, 32, 5, padding=0)
        self.relu_2 = nn.ReLU(inplace=True)
        self.maxpool_2 = nn.MaxPool2d(kernel_size=2)
        
        self.liner = nn.Linear(4*4*32, 10)
        
    def forward(self, x):
        x = x.view(x.size(0), -1)
        out = self.maxpool_1(self.relu_1(self.conv2d_1))
        out = self.maxpool_2(self.relu_2(self.conv2d_2))
        out = self.liner(out.view(x.size(0), -1))
        return out

# torch.nn.functional 定义一个相同的CNN
class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()
        
        self.conv_1_weight = nn.Parameter(torch.randn(16, 1, 5, 5))
        self.bias_1_weight = nn.Parameter(torch.randn(16))
        
        self.conv_2_weight = nn.Parameter(torch.randn(32, 16, 5, 5))
        self.bias_2_weight = nn.Parameter(torch.randn(32))
        
        self.linear_weight = nn.Parameter(torch.randn(4 * 4 * 32, 10))
        self.bias_weight = nn.Parameter(torch.randn(10))
      
    def forward(self, x):
        x = x.view(x.size(0), -1)
        out = F.conv2d(x, self.conv_1_weight, self.bias_1_weight)
        out = F.conv2d(out, self.conv_2_weight, self.bias_2_weight)
        out = F.linear(out.view(x.size(0), -1), self.linear_weight, self.bias_weight)     
#4 .在使用Dropout时，推荐使用nn.xxx，因为一般只有训练时才使用 Dropout，
# 在验证或测试时不需要使用 Dropout。使用 nn.Dropout时，如果调用 model.eval() ，
# 模型的 Dropout 层都会关闭；但如果使用 nn.functional.dropout，在调用 model.eval() 时，不会关闭 Dropout。
# 5.我们想要自定义卷积核时，是不能使用torch.nn.ConvNd 的，
# 因为它里面的权重都是需要学习的参数，没有办法自行定义。但是，我们可以使用 torch.nn.functional.conv2d()

# LeNet网络搭建实例
LeNet网络结构
![jupyter](https://img-blog.csdn.net/20180302201820978?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvamVyeWplcnlqZXJ5/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70)
假设激活函数使用relu，卷积核大小为5x5，下面我们开始尝试搭建LeNet吧

In [14]:
class LeNet(nn.Module):
    def __init__(self):
        super(self, LeNet).__init__()
        
        self.conv_1 = nn.Conv2d(1, 6, 5, padding=1)
        self.max_pool_1 = nn.MaxPool2d(2)
        
        self.conv_2 = nn.Conv2d(6, 16, 5, padding=1)
        self.max_pool_2 = nn.MaxPool2d(2)
        
        self.fc1 = nn.Linear(16*5*5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
        
    def forward(self, x):
        x = self.max_pool_1(F.relu(self.conv_1(x)))
        x = self.max_pool_2(F.relu(self.conv_2(x)))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# VGG16网络搭建实例
VGG16网络结构图如下：
![jupyter](https://img-blog.csdnimg.cn/2018121616365865.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3poYW5naGFvMzM4OQ==,size_16,color_FFFFFF,t_70)
假设激活函数为relu，卷积核大小3x3,有batch-norm操作，下面我们开始愉快地尝试搭建VGG16吧  
更多实例请参考pytorch vgg实现源码：

In [33]:
class VGG16(nn.Module):
    def __init__(self):
        super(self, VGG16).__init__()
        
        self.layer1 = nn.Sequential(nn.Conv2d(3, 64, 3, padding=1),
                                    nn.BatchNorm2d(64),
                                    nn.ReLU(inplace=True),
                                    nn.Conv2d(64, 64, 3, padding=1),
                                    nn.BatchNorm2d(64),
                                    nn.ReLU(inplace=True),
                                    nn.MaxPooling2d(2))
        self.layer2 = nn.Sequential(nn.Conv2d(64, 128, 3, padding=1),
                                    nn.BatchNorm2d(128),
                                    nn.ReLU(inplace=True),
                                    nn.Conv2d(128, 128, 3, padding=1),
                                    nn.BatchNorm2d(128),
                                    nn.ReLU(inplace=True),
                                    nn.MaxPooling2d(2))
        self.layer3 = nn.Sequential(nn.Conv2d(128, 256, 3, padding=1),
                                    nn.BatchNorm2d(256),
                                    nn.ReLU(inplace=True),
                                    nn.Conv2d(256, 256, 3, padding=1),
                                    nn.BatchNorm2d(256),
                                    nn.ReLU(inplace=True),
                                    nn.Conv2d(256, 256, 3, padding=1),
                                    nn.BatchNorm2d(256),
                                    nn.ReLU(inplace=True),
                                    nn.MaxPooling2d(2))
        self.layer4 = nn.Sequential(nn.Conv2d(256, 512, 3, padding=1),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(inplace=True),
                                    nn.Conv2d(512, 512, 3, padding=1),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(inplace=True),
                                    nn.Conv2d(512, 512, 3, padding=1),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(inplace=True),
                                    nn.MaxPooling2d(2))
        self.layer5 = nn.Sequential(nn.Conv2d(512, 512, 3, padding=1),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(inplace=True),
                                    nn.Conv2d(512, 512, 3, padding=1),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(inplace=True),
                                    nn.Conv2d(512, 512, 3, padding=1),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(inplace=True),
                                    nn.MaxPooling2d(2))
        self.fc1 = nn.Linear(7*7*512, 4096)
        self.fc2 = nn.Linear(4096, 4096)
        self.fc3 = nn.LInear(4096, 1000)
    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)
        x = self.layer5(x)
        
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.softmax(self.fc3(x))
        return x
        

# ResNet18 网络搭建实例
ResNet18网络结构如下：
![jupyter](https://img-blog.csdn.net/20180426215052446?watermark/2/text/aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3N1bnFpYW5kZTg4/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70)
ResNet有几种类型，分别为18、34、50、101、152个隐藏层，常用的有ResNet50、ResNet101、ResNet152，这里因为只是做个示范，所以以最简单ResNet18为例。
ResNet有两种跳跃结构，分别用于ResNet18、ResNet34和ResNet50、ResNet101、ResNet152，结构分别为:  
![jupyter](https://img-blog.csdn.net/20180114183212429?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvbGFucmFuMg==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)  
这两种结构分别针对ResNet34（左图）和ResNet50/101/152（右图），一般称整个结构为一个”building block“。其中左图称为“basic design”右图称为”bottleneck design”，右图目的一目了然，就是为了降低参数的数目，第一个1x1的卷积把256维channel降到64维，然后在最后通过1x1卷积恢复，整体上用的参数数目：1x1x256x64 + 3x3x64x64 + 1x1x64x256 = 69632，而不使用bottleneck的话就是两个3x3x256的卷积，参数数目: 3x3x256x256x2 = 1179648，差了16.94倍。  
不同的ResNet结构如下图：  
![jupyter](https://img-blog.csdnimg.cn/20190202101501192.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dpbnljZw==,size_16,color_FFFFFF,t_70)
假设激活函数为relu，卷积核大小3x3,有batch-norm操作，下面我们开始愉快地尝试搭建resnet18吧  
说明：ResNet有很多旁路支线可以将输入直接连到后面的层，使得后面的层可以直接学习残差，简化了学习难度。传统的卷积层和全连接层在信息传递时，或多或少会存在信息丢失，损耗等问题。ResNet将输入信息绕道传到输出，保护了信息的完整性。

In [37]:
# 官方实现
# 用于ResNet18和34的残差块，用的是2个3x3的卷积
class BasicBlock(nn.Module):
    expansion = 1

    def __init__(self, in_planes, planes, stride=1):
        super(BasicBlock, self).__init__()
        self.conv1 = nn.Conv2d(in_planes, planes, kernel_size=3,
                               stride=stride, padding=1, bias=False)
        self.bn1 = nn.BatchNorm2d(planes)
        self.conv2 = nn.Conv2d(planes, planes, kernel_size=3,
                               stride=1, padding=1, bias=False)
        self.bn2 = nn.BatchNorm2d(planes)
        self.shortcut = nn.Sequential()
        # 经过处理后的x要与x的维度相同(尺寸和深度)
        # 如果不相同，需要添加卷积+BN来变换为同一维度
        if stride != 1 or in_planes != self.expansion*planes:
            self.shortcut = nn.Sequential(
                nn.Conv2d(in_planes, self.expansion*planes,
                          kernel_size=1, stride=stride, bias=False),
                nn.BatchNorm2d(self.expansion*planes)
            )

    def forward(self, x):
        out = F.relu(self.bn1(self.conv1(x)))
        out = self.bn2(self.conv2(out))
        out += self.shortcut(x)
        out = F.relu(out)
        return out
    
    
# 用于ResNet50,101和152的残差块，用的是1x1+3x3+1x1的卷积
class Bottleneck(nn.Module):
    # 前面1x1和3x3卷积的filter个数相等，最后1x1卷积是其expansion倍
    expansion = 4

    def __init__(self, in_planes, planes, stride=1):
        super(Bottleneck, self).__init__()
        self.conv1 = nn.Conv2d(in_planes, planes, kernel_size=1, bias=False)
        self.bn1 = nn.BatchNorm2d(planes)
        self.conv2 = nn.Conv2d(planes, planes, kernel_size=3,
                               stride=stride, padding=1, bias=False)
        self.bn2 = nn.BatchNorm2d(planes)
        self.conv3 = nn.Conv2d(planes, self.expansion*planes,
                               kernel_size=1, bias=False)
        self.bn3 = nn.BatchNorm2d(self.expansion*planes)

        self.shortcut = nn.Sequential()
        if stride != 1 or in_planes != self.expansion*planes:
            self.shortcut = nn.Sequential(
                nn.Conv2d(in_planes, self.expansion*planes,
                          kernel_size=1, stride=stride, bias=False),
                nn.BatchNorm2d(self.expansion*planes)
            )

    def forward(self, x):
        out = F.relu(self.bn1(self.conv1(x)))
        out = F.relu(self.bn2(self.conv2(out)))
        out = self.bn3(self.conv3(out))
        out += self.shortcut(x)
        out = F.relu(out)
        return out


class ResNet(nn.Module):
    def __init__(self, block, num_blocks, num_classes=10):
        super(ResNet, self).__init__()
        self.in_planes = 64

        self.conv1 = nn.Conv2d(3, 64, kernel_size=3,
                               stride=1, padding=1, bias=False)
        self.bn1 = nn.BatchNorm2d(64)
        
        self.layer1 = self._make_layer(block, 64, num_blocks[0], stride=1)
        self.layer2 = self._make_layer(block, 128, num_blocks[1], stride=2)
        self.layer3 = self._make_layer(block, 256, num_blocks[2], stride=2)
        self.layer4 = self._make_layer(block, 512, num_blocks[3], stride=2)
        self.linear = nn.Linear(512*block.expansion, num_classes)

    def _make_layer(self, block, planes, num_blocks, stride):
        strides = [stride] + [1]*(num_blocks-1)
        layers = []
        for stride in strides:
            layers.append(block(self.in_planes, planes, stride))
            self.in_planes = planes * block.expansion
        return nn.Sequential(*layers)

    def forward(self, x):
        out = F.relu(self.bn1(self.conv1(x)))
        out = self.layer1(out)
        out = self.layer2(out)
        out = self.layer3(out)
        out = self.layer4(out)
        out = F.avg_pool2d(out, 4)
        out = out.view(out.size(0), -1)
        out = self.linear(out)
        return out


def ResNet18():
    return ResNet(BasicBlock, [2,2,2,2])

def ResNet34():
    return ResNet(BasicBlock, [3,4,6,3])

def ResNet50():
    return ResNet(Bottleneck, [3,4,6,3])

def ResNet101():
    return ResNet(Bottleneck, [3,4,23,3])

def ResNet152():
    return ResNet(Bottleneck, [3,8,36,3])
